# Generated by Django 3.1.7 on 2021-03-04 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvals',
            options={'verbose_name': 'Approvals'},
        ),
    ]
